### ISSUE TITLE
example code

### ISSUE THREAD

**Issue by Rakeshvcr** [NiseVoid/ploc-bvh#1]
Hi, 
I am new to Rust, I was not able to understand it properly. Is there an example code that I can refer to?
I have used bvh crate and it seems to work fine, but I also want to test this approach.

**Comment by NiseVoid** [comment]
I had an example in the readme, but it seems like it was outdated. I updated the example there and made sure it compiles. I also expanded the README a bit to explain some of the less obvious design details (like the support of multiple bounding volume types, and the use of bevy_math) of the crate.

**Comment by Rakeshvcr** [comment]
Thanks a lot!
